Implemented crud for admin
Scaler-Projects/group-9-grievance-redressal-system pull request #10
Opened 2023-11-01 21:17 UTC by upendra2610

Created crud for admin by using remote db.

2023-11-02 06:37 UTC, ajeetcloud commented on admin-management-service/src/main/java/com/scaler/adminmanagementservice/controllers/AdminController.java
> +@RequestMapping("/admins")
remove from here, its there in admin operations

2023-11-02 06:39 UTC, ajeetcloud commented on admin-management-service/src/main/java/com/scaler/adminmanagementservice/services/AdminServiceImplementation.java
> +        List<User> users = userRepository.findAll();
findAll() will give you Admin and normal user both. We need only admin.

2023-11-02 06:40 UTC, ajeetcloud requested changes
pls do the changes

2023-11-02 16:50 UTC, upendra2610 commented
I have removed the @RequestMapping and modified the findAll all the users who are admins, Please review once

2023-11-04 14:43 UTC, ajeetcloud approved these changes
LGTM

2023-11-04 14:43 UTC, merged