Added basic dependencies
Scaler-Projects/group-9-grievance-redressal-system pull request #5
Opened 2023-10-23 20:32 UTC by dembasiby

Added Spring Data JPA, MySQL adapter, Lombok, and Flyway dependencies

2023-10-24 16:34 UTC, ajeetcloud commented on user-management-service/pom.xml
> +        <dependency>
pls remove unrequired dependencies

2023-10-24 16:34 UTC, ajeetcloud requested changes
remove commented lines in pom.xml

2023-10-27 13:54 UTC, dembasiby commented on user-management-service/pom.xml
> +        <dependency>
Done

2023-10-27 13:56 UTC, dembasiby commented
Pom file cleaned

2023-11-01 13:33 UTC, closed without merging